version: '2'


services:
    web:
        image: nginx:latest
        ports:
            - "8097:80"
        volumes:
            - ./code:/code
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        build:
            context: ./docker/php
        volumes:
            - ./code:/code
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
